# Generated by Django 4.2.28 on 2026-02-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Awaiting Confirmation', 'Awaiting Confirmation'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', max_length=30),
        ),
    ]
