# Generated by Django 4.2.28 on 2026-02-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
